version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount file konfigurasi Nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Mount folder SSL
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - webapp # Pastikan nginx dimulai setelah webapp
    restart: always

  # Service untuk aplikasi web Flask
  webapp:
    # build: . 
    image: fahmidl/app-sso:latest
    # ports:
    #   - "5000:5000"
    # volumes:
    #   - .:/app
    env_file:
      - .env
    depends_on:
      - db
    # Perintah ini akan diteruskan ke 'exec "$@"' di dalam entrypoint.sh
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
    restart: always

  # Service untuk database PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ports:
    #   - "5432:5432"
    restart: always

volumes:
  postgres_data: